"""Prueba funcional de la web servida bajo /ninja-saga/, como en Pages."""
import os
from pathlib import Path
from playwright.sync_api import sync_playwright, expect

url = os.environ.get('CODEX_TEST_URL', 'http://127.0.0.1:8000/ninja-saga/')
out = Path(__file__).resolve().parents[1] / 'test-results'
out.mkdir(exist_ok=True)
with sync_playwright() as p:
    browser = p.chromium.launch()
    page = browser.new_page(viewport={'width':1440, 'height':1000})
    errors = []
    page.on('pageerror', lambda e: errors.append(str(e)))
    page.goto(url)
    page.locator('#language-welcome [data-lang="es"]').click()
    page.locator('#categories [data-category="extreme"]').click()
    expect(page.locator('.card')).to_have_count(37)
    page.screenshot(path=str(out / 'desktop.png'), full_page=True)
    page.locator('#search').fill('Sharingan')
    expect(page.locator('.card')).to_have_count(2)
    page.locator('[data-detail]').first.click()
    expect(page.locator('#detail')).to_be_visible()
    expect(page.locator('#detail-content')).to_contain_text('Tomoe Mastery')
    page.keyboard.press('Escape')
    expect(page.locator('#detail')).not_to_be_visible()
    page.locator('#reset').click()
    page.locator('[data-compare]').nth(0).click()
    page.locator('[data-compare]').nth(1).click()
    page.locator('[data-compare]').nth(2).click()
    page.locator('[data-compare]').nth(3).click()
    expect(page.locator('#selected button')).to_have_count(3)
    expect(page.locator('#toast')).to_contain_text('hasta tres')
    page.locator('#open-compare').click()
    expect(page.locator('#comparison table thead th')).to_have_count(4)
    page.screenshot(path=str(out / 'comparison.png'))
    page.keyboard.press('Escape')
    page.locator('#categories [data-category="jutsu"]').click()
    expect(page.locator('.card')).to_have_count(74)
    expect(page.locator('#compare-tray')).not_to_be_visible()
    page.locator('#search').fill('Tomb of Excalibur')
    expect(page.locator('.card')).to_have_count(2)
    page.locator('#sort').select_option('level')
    expect(page.locator('.card').first).to_contain_text('LV 50')
    page.locator('[data-detail]').first.click()
    expect(page.locator('#detail-content')).to_contain_text('350')
    page.keyboard.press('Escape')
    page.locator('#search').fill('NO_SUCH_JUTSU_123')
    expect(page.locator('#empty')).to_be_visible()
    page.locator('#empty-reset').click()
    page.locator('#effect').select_option('stun')
    assert 0 < page.locator('.card').count() < 74
    page.locator('#categories [data-category="pet"]').click()
    expect(page.locator('.card')).to_have_count(3)
    expect(page.locator('.tag.warn')).to_have_count(2)
    page.locator('#search').fill('Easter')
    page.locator('[data-detail]').click()
    expect(page.locator('#detail-content')).to_contain_text('Sin dato')
    expect(page.locator('#detail-content')).to_contain_text('25/30')
    page.keyboard.press('Escape')
    for cat,count in [('secret',32),('senjutsu',8)]:
        page.locator(f'#categories [data-category="{cat}"]').click()
        expect(page.locator('.card')).to_have_count(count)
    page.reload()
    expect(page.locator('.card')).to_have_count(8)
    page.set_viewport_size({'width':390,'height':844})
    page.locator('#categories [data-category="extreme"]').click()
    expect(page.locator('.card')).to_have_count(37)
    assert page.evaluate('document.documentElement.scrollWidth <= innerWidth')
    page.screenshot(path=str(out / 'mobile.png'),full_page=True)
    page.locator('[data-compare]').nth(0).click()
    page.locator('[data-compare]').nth(1).click()
    page.locator('#open-compare').click()
    expect(page.locator('#comparison')).to_be_visible()
    assert page.evaluate('document.documentElement.scrollWidth <= innerWidth')
    page.keyboard.press('Escape')
    page.locator('[data-detail]').first.click()
    expect(page.locator('#detail')).to_be_visible()
    assert page.evaluate('document.documentElement.scrollWidth <= innerWidth')
    page.keyboard.press('Escape')
    assert not errors, errors
    browser.close()
print('OK: categorias, busqueda, filtros, variantes, comparador, limite de 3, datos pendientes, dialogos y movil sin errores JS.')
